// Generated by Selenium IDE
import java.awt.Dimension;
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
public class REQ03CT02ValidaCadastrarAlunoDeixarRABranco<JavascriptExecutor, WebDriver> {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @SuppressWarnings("unchecked")
@Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void rEQ03CT02ValidaCadastrarAlunoDeixarRABranco() {
    driver.get("https://ts-scel.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.linkText("Alunos")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Luiz Otavio");
    driver.findElement(By.id("email")).sendKeys("luiz@fatec.com");
    driver.findElement(By.id("cep")).sendKeys("03554070");
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }
}
