// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class REQ04CT04ValidarEhPossivelCadastrarNomeCom51OuMaisCaracteres<JavascriptExecutor, WebDriver> {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void rEQ04CT04ValidarEhPossivelCadastrarNomeCom51OuMaisCaracteres() {
    driver.get("https://ts-scel.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(550, 692));
    driver.findElement(By.linkText("Alunos")).click();
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("1115");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("LuizLuizLuizLuizLuizLuizLuizLuizLuizLuizLuizLuizLuiz");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("luiz@fatec.com");
    driver.findElement(By.id("cep")).sendKeys("035");
    driver.findElement(By.id("cep")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("cep")).sendKeys("03554070");
    driver.findElement(By.cssSelector(".row:nth-child(2) > .col-md-8:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }
}
