// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class REQ10CT01VerificarUsuarioMariaFuncoesPlanejadas<WebDriver, JavascriptExecutor> {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void rEQ10CT01VerificarUsuarioMariaFuncoesPlanejadas() {
    driver.get("https://ts-scel.herokuapp.com/");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("maria");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("456");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.linkText("Empréstimo")).click();
    driver.findElement(By.id("isbn")).click();
    driver.findElement(By.id("isbn")).sendKeys("4564");
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("1115");
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("1113");
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("maria");
    driver.findElement(By.name("password")).sendKeys("456");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.linkText("Alunos")).click();
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("1115");
    driver.findElement(By.id("nome")).sendKeys("Luiz");
    driver.findElement(By.id("email")).sendKeys("luiz@fatec.com");
    driver.findElement(By.id("cep")).sendKeys("03554070");
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.findElement(By.linkText("Voltar")).click();
    driver.findElement(By.linkText("Empréstimo")).click();
    driver.findElement(By.id("isbn")).click();
    driver.findElement(By.id("isbn")).sendKeys("4564");
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("1115");
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    vars.put("win476", waitForWindow(2000));
    driver.switchTo().window(vars.get("win476").toString());
    driver.findElement(By.linkText("Devolver")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) .btn")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) .btn")).click();
    driver.findElement(By.linkText("Voltar")).click();
    driver.findElement(By.linkText("Livros")).click();
    driver.findElement(By.linkText("Voltar")).click();
    driver.findElement(By.linkText("Empréstimo")).click();
    driver.findElement(By.id("isbn")).click();
    driver.findElement(By.id("isbn")).sendKeys("4564");
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("1115");
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.manage().window().setSize(new Dimension(550, 692));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("maria");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("456");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.linkText("Alunos")).click();
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("1119");
    driver.findElement(By.id("nome")).sendKeys("Luizeto");
    driver.findElement(By.id("email")).sendKeys("luiz@fatec.com");
    driver.findElement(By.id("email")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("email")).sendKeys(Keys.TAB);
    driver.findElement(By.id("cep")).sendKeys("03554");
    driver.findElement(By.id("cep")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("cep")).sendKeys("03554070");
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.findElement(By.id("isbn")).click();
    driver.findElement(By.id("isbn")).click();
    {
      WebElement element = driver.findElement(By.id("isbn"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("isbn")).sendKeys("4564");
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("1119");
    driver.findElement(By.cssSelector(".row:nth-child(3) > .form-group")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    vars.put("win5940", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win5940").toString());
    driver.findElement(By.linkText("Devolver")).click();
    driver.findElement(By.linkText("Devolver")).click();
    driver.switchTo().window(vars.get("root").toString());
    driver.switchTo().window(vars.get("win5940").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("maria");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("456");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).click();
    {
      WebElement element = driver.findElement(By.name("username"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("username")).sendKeys("maria");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("456");
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Alunos")).click();
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("1113");
    driver.findElement(By.id("nome")).sendKeys("Luiz");
    driver.findElement(By.id("nome")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("nome")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("nome")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("nome")).sendKeys(Keys.TAB);
    driver.findElement(By.id("email")).sendKeys("luiz@fatec.com");
    driver.findElement(By.id("cep")).sendKeys("03554070");
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.findElement(By.linkText("Voltar")).click();
    driver.findElement(By.linkText("Empréstimo")).click();
    driver.findElement(By.id("isbn")).click();
    driver.findElement(By.id("isbn")).sendKeys("4564");
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("1113");
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    vars.put("win6721", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6721").toString());
    driver.findElement(By.cssSelector(".fa-sign-out-alt")).click();
  }
}
